# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.kernel.sysctl = {
    "vm.swappiness" = 10;
  };
  boot.extraModulePackages = [ ];

  # Votre partition principale (Root). La demande de mot de passe normale se fera ici.
  fileSystems."/" =
    { device = "/dev/mapper/luks-aea64bff-e40d-4f81-9033-a8d84819c241";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-aea64bff-e40d-4f81-9033-a8d84819c241" = {
    device = "/dev/disk/by-uuid/aea64bff-e40d-4f81-9033-a8d84819c241";
  };

  boot.initrd.systemd.enable = true;

  # Votre partition de démarrage (Boot)
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5886-2F30";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # Nouveau Swap avec chiffrement aléatoire jetable (généré à chaque démarrage)
  swapDevices = [{
    device = "/dev/nvme0n1p3";
    randomEncryption = {
      enable = true;
      allowDiscards = true;
    };
  }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
